version: "3.7"
services:
    # image project
    apiIclinic:
        build:
            args:
                user: Kelver
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - apiIclinic

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - apiIclinic
    # queue
    queue:
        build:
            args:
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - apiIclinic

    # redis
    redis:
        image: redis:latest
        networks:
            - apiIclinic

networks:
    apiIclinic:
        driver: bridge
